# Generated by Django 5.0 on 2023-12-18 11:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('tracking_id', models.CharField(max_length=200)),
                ('carrier', models.CharField(choices=[('DHL', 'DHL'), ('FedEx', 'FexEx'), ('UPS', 'UPS'), ('EDS', 'EDS')], max_length=10)),
                ('description', models.TextField()),
                ('address', models.CharField(max_length=400)),
                ('state', models.CharField(max_length=300)),
                ('origin', models.CharField(help_text='Country of origin', max_length=100)),
                ('destination', models.CharField(help_text='Country of destination', max_length=100)),
                ('weight', models.PositiveIntegerField(help_text='in KG')),
                ('quantity', models.IntegerField()),
                ('total_freight', models.DecimalField(decimal_places=2, max_digits=4)),
                ('shipment_medium', models.CharField(choices=[('Air', 'Air'), ('Sea', 'Sea'), ('Flight', 'Flight')], max_length=300)),
                ('pickup_date', models.DateField(auto_now=True)),
                ('pickup_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ShipmentHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('OH', 'On Hold'), ('OD', 'Out on delivery'), ('D', 'Delivered')], max_length=300)),
                ('time', models.TimeField()),
                ('remarks', models.CharField(blank=True, max_length=500)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom_admin.package')),
            ],
        ),
    ]
