# Generated by Django 5.0 on 2023-12-19 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0003_remove_package_total_freight_package_freight_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='carrier',
            field=models.CharField(choices=[('DHL', 'DHL'), ('FedEx', 'FexEx'), ('UPS', 'UPS'), ('EDS', 'EDS')], max_length=20),
        ),
        migrations.AlterField(
            model_name='package',
            name='tracking_id',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
