# Generated by Django 5.0 on 2023-12-19 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0004_alter_package_carrier_alter_package_tracking_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
