# Generated by Django 5.0 on 2023-12-19 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0005_alter_package_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='pickup_date',
            field=models.DateField(),
        ),
    ]
