# Generated by Django 5.0 on 2023-12-19 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0006_alter_package_pickup_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipmenthistory',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Pre-Transit', 'Pre-Transit'), ('In transit', 'In transit'), ('Out for delivery', 'Out for delivery'), ('On Hold', 'On Hold'), ('Delivered', 'Delivered')], default='Pending', max_length=300),
        ),
    ]
